version: "3"
services:
  mongodb-container-un:
    image: mongo
    container_name: mongodb-container-un
    ports:
      - 28000:27017
  springboot-avec-mongodb-container-un:
    image: guillaumelhg/springboot-avec-mongodb:v3
    container_name: springboot-avec-mongodb-container-un
    ports:
      - 8090:8083
    links:
      - mongodb-container-un
    extra_hosts:
      - host.docker.internal:host-gateway